### ISSUE TITLE
Too many levels of symbolic links (libanopa.so.0 points to self)

### ISSUE THREAD

**Issue by linsam** [jjk-jacky/anopa#2]
I found this while making a yocto recipe for anopa, but the error also shows up if I run `make install` to the same location twice.

During the install, the following is run (assuming DESTDIR=/opt):

```
./tools/install.sh -D -m 755 libanopa.so /opt/lib/libanopa.so.0.4.0 && \
./tools/install.sh -l libanopa.so.0.4.0 /opt/lib/libanopa.so.0.4 && \
./tools/install.sh -l libanopa.so.0.4 /opt/lib/libanopa.so.0 && \
./tools/install.sh -l libanopa.so.0 /opt/lib/libanopa.so.0 && \
exec ./tools/install.sh -l libanopa.so.0 /opt/lib/libanopa.so
```

Note that libanopa.so.0 links to libanopa.so.0, overwriting the link from libanopa.so.0 to libanopa.so.0.4.

This comes from the Makefile setting the various version subs:

```
  version_m := $(basename $(version))
  version_M := $(basename $(version_m))
  version_l := $(basename $(version_M))
```

and then using them for install:

```
$(DESTDIR)$(dynlibdir)/lib%.so: lib%.so
    $(INSTALL) -D -m 755 $< $@.$(version) && \ 
    $(INSTALL) -l $<.$(version) $@.$(version_m) && \ 
    $(INSTALL) -l $<.$(version_m) $@.$(version_M) && \ 
    $(INSTALL) -l $<.$(version_M) $@.$(version_l) && \ 
    exec $(INSTALL) -l $<.$(version_l) $@
```

However, the first `version` comes from `config.mak` which comes from `package/info` which only sets 3 levels of version instead of 4: `0.4.0`.

This results in `version_l` being equal to `version_M`.

Either removing the line in the Makefile that links version_l to version_M or setting the version to 0.4.0.0 in package/info resolves this.

I don't know which approach is better, so I haven't made a patch.

**Comment by jjk-jacky** [comment]
woops... yeah, there's only 3 version numbers, but the Makefile was
originaly written for 4, and I obviously never really tested that case;
My bad.

The version_l bit needs to go; Just pushed a fix to branch next,
thanks!

**Comment by linsam** [comment]
Tested build of next branch in Yocto. The build runs without issue, and the correct symlinks are installed. Thanks!
