### ISSUE TITLE
aa-tty in aa-stage2 fails if more than one console specified to kernel

### ISSUE THREAD

**Issue by linsam** [jjk-jacky/anopa#3]
When building a yocto-based image for ARM based QEMU, and running with their runqemu script, the options passed to the kernel include 

```
--append "root=/dev/vda rw console=ttyAMA0,115200 console=tty ip=192.168.7.2::192.168.7.1:255.255.255.0 mem=128M highres=off rootfstype=ext4"
```

(at least, when using raspberry-pi layer stuff, which I presume is where it got the notion of ttyAMA0)

Anopa then errors on startup with `Error: System initialization failed -> Trying to open a shell...`.

In the boot log, we get `redirfd: fatal: unable to open /dev/ttyAMA0 tty0: No such file or directory`.

It appears that when console is specified multiple times to the kernel command line, all of the consoles end up in /sys/class/tty/console/active, instead of just the first or last one as one might expect. I don't know if this is changed behaviour from old kernels, I'm only testing against 4.1.15-yocto-standard at the moment.

The list of consoles appears to be space separated (typed because qemu gives graphics only):

```
hexdump -C /sys/class/tty/console/active
00000000 74 74 79 41 4d 41 30 20  74 74 79 30 0a            |ttyAMA0 tty0.|
0000000d
```

Generally, I think the last entry in the active list would be most convenient for users of bootloaders and emulation commands that allow kernel command line parameters be appended but not replaced.

**Comment by jjk-jacky** [comment]
Thanks for the great report!

Yeah, I missed that /sys/class/tty/console/active actually is a list of
devices, the last one being indeed the active one.

Just pushed a fix to branch next,
Thanks!

**Comment by linsam** [comment]
I just tested the next branch in my VM build. Works great! Thanks!
