### ISSUE TITLE
occasional memory corruption in aa-status

### ISSUE THREAD

**Issue by linsam** [jjk-jacky/anopa#5]
When running `aa-status -a` or `aa-status -aL` I sometimes get the following

`*** Error in 'aa-status': malloc(): memory corruption: 0x0805d070 ***
Aborted`

I have noticed that it seems to persist with a generated image. Sometimes when I make an image with anopa, it works fine with no issues. Other times, it will fail every time in a given image. At the moment, I made an .iso and .ext4 pair of images from the same build and the .ext4 is fine, but the .iso is exhibiting this. At all times, I am building for i586 architecture and am running the image in qemu.

I also finally got an image that had both debugging symbols for anopa and gdb. Attached is a gdb session showing the stack trace.
[aa-status-gdb-session.txt](https://github.com/jjk-jacky/anopa/files/465576/aa-status-gdb-session.txt)

**Comment by linsam** [comment]
Forgot to mention: this is built from the next branch, commit id 3a13f4d31fc5e8c7173100b6be78d92105edff61

A copy of the iso image exhibiting this can be found at http://linsam.homelinux.com/core-image-test1-qemux86-20160910052820.iso
(112MiB) (Note, for some strange reason, the old web server there claims the file is text/plain; let me know if you have trouble downloading it)

I run it using `qemu-system-i386 -cdrom core-image-test1-qemux86-20160910052820.iso -show-cursor -usb -usbdevice tablet -vga vmware -no-reboot -serial stdio -m 256`

**Comment by linsam** [comment]
I think I found the problem. In src/libanopa/service_status.c line 60, there is
`svst->sa.s[svst->sa.len] = '\0'`; however, at this point in my execution, the struct stalloc_s `svst->sa` has a `len` of 20 _and_ an `a` of 20, meaning that all 20 bytes of 20 allocated are in use. Setting index 20 to 0 is writing past the end of the allocated data by a byte.

In my runs, that byte is 153 prior to being set to 0, and is the lsb of the `size` member of a `struct  malloc_chunk` in my libc. If I leave it alone, the next attempted reallocation (in the previous stack trace) dies detecting corruption. If I set it back to 153 in the debugger right after it was set to 0, the program completes successfully with no error.

One thing I don't follow with this, is that the `size` member of the malloc_chunk is at offset 4 on my machine, not 0, which should indicate that the first member `prev_size` would also have been corrupt by the file read that happened before the bad null termination.

I traced this by setting a watchpoint on the address of the corrupt size member, which last halted at the null terminator write. Here are some relevant excerpts:

At the writing of the null:

```
58      tain_now_g ();
59
60      svst->sa.s[svst->sa.len] = '\0';
61      if (svst->sa.len < AA_SVST_FIXED_SIZE + AA_SVST_MAX_MSG_SIZE + 1)
62          svst->sa.len++;
63

(gdb) print &svst->sa.s[svst->sa.len]
$47 = 0x805d06c ""
(gdb) print svst->sa.len
$48 = 20
```

Later during the next reallocation

```
3463          while ((victim = unsorted_chunks (av)->bk) != unsorted_chunks (av))
3464            {
3465              bck = victim->bk;
3466              if (__builtin_expect (victim->size <= 2 * SIZE_SZ, 0)
3467                  || __builtin_expect (victim->size > av->system_mem, 0))
3468                malloc_printerr (check_action, "malloc(): memory corruption",
3469                                 chunk2mem (victim), av);
3470              size = chunksize (victim);
3471
3472              /*

(gdb) p &victim->size
$49 = (size_t *) 0x805d06c
```

I haven't figured out the structure of things to know if it should be allocating an extra byte (or doing a string concatenate for the NULL), if it should be setting the 20th byte to null (index 19, or len-1), or if it doesn't need to be terminated at all (I might be lucky that mine runs without the NULL).

**Comment by jjk-jacky** [comment]
Yes, good catch!

This was indeed a nasty bug where I guess I assumed the allocated data
was always the maximum possible, while it obviously isn't
(openreadfileclose() only allocates as needed ofc), which could lead to
writing outside the allocated area as you've found out.

I just pushed a fix on branch next that should fix this, please try it
& let me know.

Thanks for the great report.

**Comment by linsam** [comment]
Fix looks good. I built 5 or so images, all of which are working. I also did a single run through gdb around the area and observed that the NULL terminator is now in-bounds (21 bytes allocated instead of 20 in my case now).  Thanks for the quick fix!
