### ISSUE TITLE
aa-enable'd long-run services don't work post-boot without running s6-svscanctl by hand

### ISSUE THREAD

**Issue by linsam** [jjk-jacky/anopa#6]
I'm not sure if this is a bug or a feature request (or I might misunderstand how to do this).

If I add a new service after boot-time (that is, s6-svscan is already running), and enable the service with aa-enable, anopa cannot obtain the status of the service, and trying to start it fails. This seems to be because s6-svscan isn't told about it, so there is no s6-supervise for the new service, and so there is nothing with which anopa can communicate for getting status to instruct a change of state.

I can think of 2 fixes: either the stage-1 script should launch s6-svscan to look for changes (not use `-t 0`), or aa-enable should notify s6-svscan about the change. I'd worry about a race condition between s6-svscan and anopa trying to create the supervise directory for the service in the first fix, so the second fix is probably better.

Currently I'm dealing with this by running `s6-svscanctl -an /run/services/.scandir` after running `aa-enable`.

I expect that notifying s6-svscan automatically all the time would break the part of stage-1 where enable is called prior to s6-svscan running in order to pre-populate the repository. For user experience, I'd suggest having the notification be default and have a flag to not do it, which would be used in stage1. However, if backwards compatibility is an issue, I'd be ok having to give a flag when running aa-enable on a working system (easier than having to type out the scandir for s6-svscanctl).

Example session:

```
root@192:/etc/anopa/services# aa-status -aL
Service       Type    Since               Status
uncaught-logs longrun 2016-09-11 20:24:10 Up (PID 72)
gettycon      longrun 2016-09-11 20:24:10 Up (PID 80)
root@192:/etc/anopa/services# aa-enable gettycon2
Enabled: gettycon2

==> aa-enable: Completed
  -> Enabled: 1
root@192:/etc/anopa/services# aa-status -aL
Service       Type    Since               Status
gettycon2     longrun -                   Unknown status
uncaught-logs longrun 2016-09-11 20:24:10 Up (PID 72)
gettycon      longrun 2016-09-11 20:24:10 Up (PID 80)
root@192:/etc/anopa/services# aa-start gettycon2
Starting gettycon2...
==> ERROR: gettycon2: Failed to communicate with s6: Failed to subscribe to eventdir

==> aa-start: Completed.
  -> Failed: gettycon2
root@192:/etc/anopa/services# aa-status -aL
Service       Type    Since               Status
uncaught-logs longrun 2016-09-11 20:24:10 Up (PID 72)
gettycon      longrun 2016-09-11 20:24:10 Up (PID 80)
gettycon2     longrun 2016-09-11 20:33:37 Starting failed: Failed to communicate with s6: Failed to subscribe to eventdir
root@192:/etc/anopa/services# s6-svscanctl -an /run/services/.scandir/
root@192:/etc/anopa/services# aa-status -aL
Service       Type    Since               Status
uncaught-logs longrun 2016-09-11 20:24:10 Up (PID 72)
gettycon      longrun 2016-09-11 20:24:10 Up (PID 80)
gettycon2     longrun 2016-09-11 20:34:19 Down & Ready (exitcode 0)
root@192:/etc/anopa/services# aa-start gettycon2
Starting gettycon2...
==> gettycon2: Started

==> aa-start: Completed.
  -> Started: 1
root@192:/etc/anopa/services# aa-status -aL
Service       Type    Since               Status
uncaught-logs longrun 2016-09-11 20:24:10 Up (PID 72)
gettycon      longrun 2016-09-11 20:24:10 Up (PID 80)
gettycon2     longrun 2016-09-11 20:34:24 Up (PID 97)
root@192:/etc/anopa/services# 
```

**Comment by jjk-jacky** [comment]
Right, I would file that under "feature request" That is to say, the
behavior you describe is what was intended: aa-enable only creates
servicedirs, so if you add some to an active repodir(/scandir), i.e. w/
a running s6-svscan, you need to run `s6-svscanctl -a` so it rescans
the scandir.

But it might indeed not be a bad idea to add a -a switch to aa-enable,
so that it alarms s6-svscan automatically as a last step, yes. I'll
see to add that.

**Comment by linsam** [comment]
Tested, works. Thanks!
